# dataset config : Sequential Recommendation
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp
load_col:
    inter: [user_id, item_id, timestamp]
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
MAX_ITEM_LIST_LENGTH: 200

user_inter_num_interval: "[5,inf)"
item_inter_num_interval: "[5,inf)"

# model config
embedding_size: 64              # (int) The input and output hidden size.
layer_norm_eps: 1e-12           # (float) The value added to the denominator for numerical stability.
prototype_size: 50              # (int) The size of latent prototypes.
interest_size: 3                # (int) The number of intentions.
tau_ratio: 0.1                  # (float) The tau value for temperature tuning.
reg_loss_ratio: 0.5             # (float) The L2 regularization weight.
loss_type: 'CE'                 # (str) The type of loss function. Range in ['BPR', 'CE'].

# Training and evaluation config
epochs: 500
train_batch_size: 1024
eval_batch_size: 128
train_neg_sample_args: ~
eval_args:
    group_by: user
    order: TO
    split: {'LS': 'valid_and_test'}
    mode: full
metrics: ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk: [1, 5, 10, 20, 50]
valid_metric: MRR@10
metric_decimal_place: 4

# Env
gpu_id: '3'
show_progress: False
save_dataloaders: 'saved/'
save_dataset: True