# dataset config : Sequential Recommendation
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp
load_col:
    inter: [user_id, item_id, timestamp]
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
MAX_ITEM_LIST_LENGTH: 200

user_inter_num_interval: "[5,inf)"
item_inter_num_interval: "[5,inf)"

# model config
embedding_size: 64              # (int) The embedding size of users and items.
loss_type: 'BPR'                # (str) The type of loss function. Range in ['BPR'].

# Training and evaluation config
epochs: 500
train_batch_size: 1024
eval_batch_size: 4096
train_neg_sample_args: 
    distribution: 'uniform'
    sample_num: 1
eval_args:
    group_by: user
    order: TO
    split: {'LS': 'valid_and_test'}
    mode: full
metrics: ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk: [1, 5, 10, 20, 50]
valid_metric: MRR@10
metric_decimal_place: 4

# Env
gpu_id: '3'
show_progress: False
save_dataloaders: 'saved/'
save_dataset: True